import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useCompany } from '../../context/CompanyContext'
import './LoggingInFlow.css'

export function Verify2FAPage() {
  const navigate = useNavigate()
  const { flowPath } = useCompany()
  const [code, setCode] = useState('')
  const [rememberBrowser, setRememberBrowser] = useState(false)

  const handleContinue = (e) => {
    e.preventDefault()
    if (code.length === 6) {
      navigate(flowPath('/flow/dashboard'))
    }
  }

  return (
    <div className="logging-in-2fa">
      <div className="logging-in-2fa-card">
        <span className="logging-in-2fa-icon">🔐</span>
        <h1 className="logging-in-2fa-title">Verify it&apos;s you with your authenticator app</h1>
        <p className="logging-in-2fa-desc">
          To continue, enter the 6-digit code generated by your authenticator app.
        </p>
        <form onSubmit={handleContinue} className="logging-in-2fa-form">
          <div className="logging-in-field">
            <label>6-digit code</label>
            <input
              type="text"
              inputMode="numeric"
              maxLength={6}
              value={code}
              onChange={(e) => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
              placeholder="000000"
              className="logging-in-2fa-input"
            />
          </div>
          <div className="logging-in-2fa-actions">
            <button type="button" className="logging-in-link" onClick={() => navigate(flowPath('/flow/logging-in'))}>
              Choose a different method
            </button>
            <button
              type="submit"
              className="logging-in-btn-primary"
              disabled={code.length !== 6}
            >
              Continue
            </button>
          </div>
          <label className="logging-in-checkbox">
            <input
              type="checkbox"
              checked={rememberBrowser}
              onChange={(e) => setRememberBrowser(e.target.checked)}
            />
            <span>Remember this browser for 48 hours</span>
            <span className="logging-in-info-icon" title="Your session will be remembered">ⓘ</span>
          </label>
        </form>
      </div>
    </div>
  )
}
